DROP DATABASE IF EXISTS modjoy_db;
CREATE DATABASE modjoy_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE modjoy_db;

-- 1. ตารางคณะ
CREATE TABLE FACULTYS (
    FACULTY_ID INT AUTO_INCREMENT PRIMARY KEY,
    FACULTY_NAME VARCHAR(100) NOT NULL UNIQUE
);

-- 2. ตารางสถานที่
CREATE TABLE LOCATIONS (
    LOCATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOCATION_NAME VARCHAR(100) NOT NULL UNIQUE
);

-- 3. ตารางแท็ก
CREATE TABLE TAGS (
    TAG_ID INT AUTO_INCREMENT PRIMARY KEY,
    TAG_NAME VARCHAR(50) NOT NULL UNIQUE
);

-- 4. ตารางผู้ใช้งาน (อิงตาม Diagram ของคุณ)
CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_EMAIL VARCHAR(50) NOT NULL UNIQUE,
    USER_FNAME VARCHAR(50) NOT NULL,
    USER_LNAME VARCHAR(50) NOT NULL,
    USER_PASSWORD VARCHAR(50) NOT NULL,
    USER_FACULTY INT, -- FK
    USER_YEAR INT NOT NULL DEFAULT 1,
    USER_DESCRIPTION TEXT,
    USER_CREDIT_SCORE INT DEFAULT 100,
    USER_ROLE ENUM('student', 'admin') DEFAULT 'student',
    USER_IMG VARCHAR(255) DEFAULT '/Resource/img/profile.png',
    
    FOREIGN KEY (USER_FACULTY) REFERENCES FACULTYS(FACULTY_ID) ON DELETE SET NULL
);

-- 5. ตารางห้องกิจกรรม
CREATE TABLE ROOMS (
    ROOM_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROOM_TITLE VARCHAR(100) NOT NULL,
    ROOM_EVENT_START_TIME TIME NOT NULL,
    ROOM_EVENT_END_TIME TIME NOT NULL,
    ROOM_EVENT_DATE DATE NOT NULL,
    ROOM_EVENT_LOCATION INT, -- FK
    ROOM_DESCRIPTION TEXT,
    ROOM_LEADER_ID INT NOT NULL, -- FK
    ROOM_CHECKIN_CODE VARCHAR(6),
    ROOM_CHECKIN_EXPIRE DATETIME,
    ROOM_CAPACITY INT NOT NULL,
    ROOM_CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ROOM_IMG VARCHAR(255) DEFAULT '/Resource/img/bangmod.png',
    
    FOREIGN KEY (ROOM_LEADER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ROOM_EVENT_LOCATION) REFERENCES LOCATIONS(LOCATION_ID) ON DELETE SET NULL
);

-- 6. ตารางสมาชิกในห้อง (User <-> Room)
CREATE TABLE ROOMMEMBERS (
    ROOM_ID INT,
    USER_ID INT,
    ROOMMEMBER_JOINED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ROOMMEMBER_CHECKIN_TIME DATETIME,
    ROOMMEMBER_STATUS ENUM('present', 'absent', 'pending') DEFAULT 'pending',
    
    PRIMARY KEY (ROOM_ID, USER_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 7. ตารางจับคู่ห้อง-แท็ก
CREATE TABLE ROOMTAGS (
    ROOM_ID INT,
    TAG_ID INT,
    PRIMARY KEY (ROOM_ID, TAG_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES TAGS(TAG_ID) ON DELETE CASCADE
);

-- 8. ตารางจับคู่ผู้ใช้-แท็ก
CREATE TABLE USERTAGS (
    USER_ID INT,
    TAG_ID INT,
    PRIMARY KEY (USER_ID, TAG_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES TAGS(TAG_ID) ON DELETE CASCADE
);

-- --- ข้อมูลเริ่มต้น (Seed Data) ---
INSERT INTO FACULTYS (FACULTY_NAME) VALUES ('ครุศาสตร์อุตสาหกรรมและเทคโนโลยี'),('วิทยาลัยสหวิทยาการ'),('วิทยาศาสตร์'),('วิศวกรรมศาสตร์'),('สถาบันวิทยาการหุ่นยนต์ภาคสนาม'),('สถาปัตยกรรมศาสตร์และการออกแบบ'),('เทคโนโลยีสารสนเทศ');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('N1'),('N2'),('N3'),('N4'),('N5'),('N6'),('N7'),('N8'),('N9'),('N10'),('N11'),('N12'),('N13'),('N14'),('N15'),('N16'),('N17'),('N18'),('N19'),('N20'),('S1'),('S2'),('S3'),('S4'),('S5'),('S6'),('S7'),('S8'),('S9'),('S10'),('S11'),('S12'),('S13'),('S14'),('S15');
INSERT INTO TAGS (TAG_NAME) VALUES ('Calculus'), ('Physics'), ('Coding'), ('Board Game'), ('Badminton'), ('Music');